// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuqCusnBTfeuX3SJZtgqu77LE1dFn43qc',
    appId: '1:872353968819:web:69864883c87640657276c6',
    messagingSenderId: '872353968819',
    projectId: 'attendance-app-fac38',
    authDomain: 'attendance-app-fac38.firebaseapp.com',
    storageBucket: 'attendance-app-fac38.appspot.com',
    measurementId: 'G-VMVXCBWEZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAb24z9PhaSvUtgemaAIZ-evh6XO2EUcc',
    appId: '1:872353968819:android:22f8d947eb1ff8737276c6',
    messagingSenderId: '872353968819',
    projectId: 'attendance-app-fac38',
    storageBucket: 'attendance-app-fac38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNbep0F-mqn8ft1r_pq_m2HVtZn5VjME',
    appId: '1:872353968819:ios:d92e41cc81fc81327276c6',
    messagingSenderId: '872353968819',
    projectId: 'attendance-app-fac38',
    storageBucket: 'attendance-app-fac38.appspot.com',
    iosBundleId: 'com.example.attendanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNbep0F-mqn8ft1r_pq_m2HVtZn5VjME',
    appId: '1:872353968819:ios:d92e41cc81fc81327276c6',
    messagingSenderId: '872353968819',
    projectId: 'attendance-app-fac38',
    storageBucket: 'attendance-app-fac38.appspot.com',
    iosBundleId: 'com.example.attendanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuqCusnBTfeuX3SJZtgqu77LE1dFn43qc',
    appId: '1:872353968819:web:bc6386ea4d1cb6837276c6',
    messagingSenderId: '872353968819',
    projectId: 'attendance-app-fac38',
    authDomain: 'attendance-app-fac38.firebaseapp.com',
    storageBucket: 'attendance-app-fac38.appspot.com',
    measurementId: 'G-N7SS79LQL3',
  );
}
